# Generated by Django 6.0.6 on 2026-08-19 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_cash_tendered_order_change_returned'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='change_notes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tendered_notes',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
