# Generated by Django 6.0.6 on 2026-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR'), ('CARD', 'Debit / Credit Card'), ('NET_BANKING', 'Net Banking'), ('COD', 'Cash on Delivery'), ('KHATA', 'Khata / Customer Credit')], default='CASH', max_length=20),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI / QR'), ('CARD', 'Debit / Credit Card'), ('NET_BANKING', 'Net Banking'), ('COD', 'Cash on Delivery'), ('KHATA', 'Khata / Customer Credit')], max_length=20),
        ),
    ]
