# Generated by Django 6.0.6 on 2026-08-21 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0002_purchaseorder_gst_mode_purchaseorder_tax_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
