# Generated by Django 6.0.6 on 2026-08-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Store Administrator / Owner')], default='ADMIN', max_length=20),
        ),
    ]
