# Generated by Django 6.0.6 on 2026-08-19 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('OPENING_FLOAT', 'Opening Cash / Float'), ('CASH_IN', 'Cash Added / Deposit'), ('CASH_OUT', 'Cash Withdrawn / Taken Out'), ('SUPPLIER_PAYMENT', 'Supplier Cash Payment'), ('EXPENSE', 'Expense Cash Payment'), ('BILL_SALE', 'POS Cash Bill Sale'), ('KHATA_PAYMENT', 'Khata Customer Cash Receipt')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
