# Generated by Django 6.0.6 on 2026-08-21 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_smartnotification_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='home_cash_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
