# Generated by Django 6.0.6 on 2026-08-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_storesetting_home_cash_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='attendance_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
