# Generated by Django 6.0.6 on 2026-08-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_attendance_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='otp_email',
            field=models.EmailField(blank=True, default='admin@tulsimart.com', max_length=254, null=True),
        ),
    ]
