# Generated by Django 5.0.14 on 2026-08-26 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attendance_data',
        ),
        migrations.RemoveField(
            model_name='user',
            name='hire_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salary',
        ),
        migrations.AddField(
            model_name='user',
            name='currency_symbol',
            field=models.CharField(default='₹', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='gstin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='store_name',
            field=models.CharField(default='Tulsi Mart', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='tagline',
            field=models.CharField(default='Fresh Groceries & Daily Needs', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Store Administrator / Owner'), ('STORE_OWNER', 'Store Owner'), ('STORE_MANAGER', 'Store Manager'), ('STORE_MANAGEMENT', 'Store Management'), ('CASHIER', 'Cashier / Billing Staff'), ('DELIVERY', 'Delivery Staff')], default='ADMIN', max_length=50),
        ),
    ]
