# Generated by Django 5.0.14 on 2026-08-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_storesetting_bank_account_number_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
