# Generated by Django 5.0.14 on 2026-08-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreSetting',
        ),
    ]
