# Generated by Django 5.0.14 on 2026-08-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_activitylog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Tulsi Mart', max_length=200)),
                ('tagline', models.CharField(default='Fresh Groceries & Supermarket', max_length=300)),
                ('store_logo', models.CharField(default='/logo.png', max_length=500)),
                ('address', models.TextField(default='Shop No. 12-14, Heritage Plaza, MG Road')),
                ('city', models.CharField(default='Mumbai', max_length=100)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('pincode', models.CharField(default='400001', max_length=20)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=50)),
                ('email', models.EmailField(default='contact@tulsimart.com', max_length=254)),
                ('gst_number', models.CharField(default='27AABCT8899F1Z4', max_length=50)),
                ('pan_number', models.CharField(default='AABCT8899F', max_length=50)),
                ('invoice_prefix', models.CharField(default='TM-INV-', max_length=30)),
                ('invoice_terms', models.TextField(default='Thank you for shopping at Tulsi Mart! 100% Quality Guarantee. Exchanges valid within 24 hours with original invoice.')),
                ('show_logo_on_invoice', models.BooleanField(default=True)),
                ('auto_print_invoice', models.BooleanField(default=False)),
                ('tax_enabled', models.BooleanField(default=True)),
                ('default_gst_rate', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('prices_include_tax', models.BooleanField(default=False)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('currency_code', models.CharField(default='INR', max_length=10)),
                ('payment_cash_enabled', models.BooleanField(default=True)),
                ('payment_upi_enabled', models.BooleanField(default=True)),
                ('payment_card_enabled', models.BooleanField(default=True)),
                ('bank_name', models.CharField(default='HDFC Bank', max_length=150)),
                ('account_number', models.CharField(default='50200012345678', max_length=100)),
                ('ifsc_code', models.CharField(default='HDFC0001234', max_length=50)),
                ('upi_id', models.CharField(default='tulsimart@hdfcbank', max_length=100)),
                ('theme_mode', models.CharField(default='light', max_length=20)),
                ('primary_color', models.CharField(default='#384959', max_length=30)),
                ('security_require_otp', models.BooleanField(default=False)),
                ('security_session_timeout', models.IntegerField(default=30)),
                ('home_cash_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Setting',
                'verbose_name_plural': 'Store Settings',
            },
        ),
    ]
