# Generated by Django 5.0.14 on 2026-08-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_storesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(help_text='Email for OTP delivery', max_length=254)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin / Store Owner'), ('STORE_MANAGER', 'Store Manager'), ('CASHIER', 'Cashier / Billing Staff')], default='ADMIN', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('require_otp', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'login',
                'ordering': ['-created_at'],
            },
        ),
    ]
