# Generated by Django 5.0.14 on 2026-08-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_loginaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCashTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('DEPOSIT', 'Manual Cash Deposit (ઘરે રોકડ જમા)'), ('WITHDRAWAL', 'Manual Cash Withdrawal (ઘરેથી રોકડ ઉપાડ)'), ('SWEEP', 'Auto EOD Sweep from Gulla (ગલ્લામાંથી ઓટો ટ્રાન્સફર)')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('denomination_counts', models.JSONField(blank=True, default=dict, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by_name', models.CharField(default='Store Owner', max_length=150)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
