# Generated by Django 5.0.14 on 2026-09-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_homecashtransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='auto_1130_sweep_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
