# Generated by Django 5.0.14 on 2026-09-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_storesetting_auto_1130_sweep_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banktransaction',
            name='transaction_type',
            field=models.CharField(choices=[('UPI_IN', 'POS UPI / Customer Payment'), ('CARD_IN', 'POS Card / Terminal Payment'), ('SUPPLIER_PAYOUT', 'Supplier Bank / UPI Payout'), ('EXPENSE_PAYOUT', 'Store Bank / UPI Expense'), ('DEPOSIT', 'Admin Capital / Cash Deposit to Bank'), ('WITHDRAWAL', 'Admin Bank Withdrawal to Cash')], max_length=30),
        ),
    ]
