# Generated by Django 6.0.6 on 2026-08-18 13:48

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LOW_STOCK', 'Low Stock Alert'), ('OUT_OF_STOCK', 'Out of Stock Alert'), ('EXPIRY', 'Product Expiry Alert'), ('PENDING_PAYMENT', 'Pending Payment Alert'), ('NEW_ORDER', 'New Order Received'), ('RETURN_REQ', 'Return Request'), ('PENDING_DELIVERY', 'Pending Delivery Alert'), ('GENERAL', 'System Notice')], default='GENERAL', max_length=30)),
                ('priority', models.CharField(choices=[('HIGH', 'High Priority'), ('MEDIUM', 'Medium Priority'), ('LOW', 'Low Priority')], default='MEDIUM', max_length=10)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(default='Tulsi Mart', max_length=150)),
                ('tagline', models.CharField(default='Fresh Groceries & Daily Needs', max_length=255)),
                ('logo_url', models.CharField(default='/logo.png', max_length=500)),
                ('phone', models.CharField(default='+91 98765 43210', max_length=30)),
                ('email', models.EmailField(default='contact@tulsimart.com', max_length=254)),
                ('address', models.TextField(default='Shop No. 12, Green Park Avenue, Main Market, Mumbai, MH - 400001')),
                ('gstin', models.CharField(default='27AABCT1234F1Z8', max_length=30)),
                ('currency_symbol', models.CharField(default='₹', max_length=10)),
                ('invoice_prefix', models.CharField(default='TM-INV-', max_length=20)),
                ('invoice_footer_terms', models.TextField(default='Thank you for shopping with Tulsi Mart! Fresh goods guarantee. Goods once sold can only be returned within 24 hours with original invoice.')),
                ('tax_percentage_default', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('delivery_charge_flat', models.DecimalField(decimal_places=2, default=40.0, max_digits=8)),
                ('free_delivery_above', models.DecimalField(decimal_places=2, default=500.0, max_digits=8)),
                ('low_stock_threshold_default', models.PositiveIntegerField(default=10)),
                ('enable_notifications', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('ADMIN', 'Super Admin / Store Owner'), ('CASHIER', 'Cashier / POS Operator'), ('INVENTORY_MGR', 'Inventory Manager'), ('DELIVERY_MGR', 'Delivery Manager'), ('SALES_MGR', 'Sales & Accounts Manager')], default='ADMIN', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('avatar', models.CharField(blank=True, max_length=500, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('is_staff_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('module', models.CharField(max_length=100)),
                ('details', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
