# Generated by Django 6.0.6 on 2026-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cashregisterentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashregisterentry',
            name='denomination_counts',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
