# Generated by Django 6.0.6 on 2026-08-21 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cashregisterentry_denomination_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Store Administrator / Owner'), ('STORE_OWNER', 'Store Owner'), ('STORE_MANAGER', 'Store Manager'), ('STORE_MANAGEMENT', 'Store Management'), ('CASHIER', 'Cashier / Billing Staff'), ('DELIVERY', 'Delivery Staff'), ('Admin', 'Admin'), ('Store Owner', 'Store Owner'), ('Store Manager', 'Store Manager'), ('Store Management', 'Store Management'), ('Cashier', 'Cashier'), ('Delivery Staff', 'Delivery Staff')], default='CASHIER', max_length=50),
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('UPI_IN', 'POS UPI / Customer Payment'), ('SUPPLIER_PAYOUT', 'Supplier Bank / UPI Payout'), ('EXPENSE_PAYOUT', 'Store Bank / UPI Expense'), ('DEPOSIT', 'Admin Capital / Cash Deposit to Bank'), ('WITHDRAWAL', 'Admin Bank Withdrawal to Cash')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(default='HDFC Store Primary Bank', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
