# Generated by Django 6.0.6 on 2026-08-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_user_role_banktransaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SmartNotification',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Store Administrator / Owner'), ('STORE_OWNER', 'Store Owner'), ('STORE_MANAGER', 'Store Manager'), ('STORE_MANAGEMENT', 'Store Management'), ('CASHIER', 'Cashier / Billing Staff'), ('DELIVERY', 'Delivery Staff')], default='CASHIER', max_length=50),
        ),
    ]
