# Generated by Django 5.0.14 on 2026-08-27 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='bank_account_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='bank_branch',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='bank_ifsc',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='bank_name',
            field=models.CharField(default='HDFC Store Primary Bank', max_length=100),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='theme_mode',
            field=models.CharField(default='light', max_length=20),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='upi_id',
            field=models.CharField(blank=True, default='tulsimart@upi', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
