# Generated by Django 5.0.14 on 2026-08-27 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_storesetting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='banktransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='cashregisterentry',
            name='created_by',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cashregisterentry',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
